AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CloudTrailBucketName:
    Description: Enter S3Bucket Name for CloudTrail
    Type: String
Resources:
# ------------------------------------------------------------#
#  CloudTrail 
# ------------------------------------------------------------# 
  CloudTrail:
    DependsOn:
      - BucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName:
        Ref: CloudTrailBucket
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      
# ------------------------------------------------------------#
#  S3 Bucket
# ------------------------------------------------------------#     
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    #DeletionPolicy: Retain
    Properties:
      BucketName: !Ref CloudTrailBucketName
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: CloudTrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              !Sub |-
                arn:aws:s3:::${CloudTrailBucket}
          -
            Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource:
              !Sub |-
                arn:aws:s3:::${CloudTrailBucket}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control